version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:11.9.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Gulp CI
          command: yarn gulp ci
  deploy:
    executor: node-executor
    steps:
      - run:
          name: Semantic Release
          command: ./node_modules/.bin/semantic-release
