version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:11.9.0

commands:
  run_gulp_ci:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Gulp CI
          command: yarn gulp ci
  semantic_release:
    steps:
      - run:
          name: Semantic Release
          command: ./node_modules/.bin/semantic-release

jobs:
  build:
    executor: node-executor
    steps:
      - run_gulp_ci
  deploy:
    executor: node-executor
    steps:
      - run_gulp_ci
      - semantic_release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
